### ISSUE TITLE
Create the project layout

### ISSUE THREAD

**Issue by virtualtam** [shaarli/python-shaarli-client#2]
- [x] #1 - changelog, readme, base packaging info
- [x] #3 Sphinx documentation stub
- [x] #3 RTFD integration
- [x] #5 Tox testing automation
- [x] #5 Travis CI integration
- [x] #6 Static analysis tools (Pylint, Pydocstyle, Pycodestyle, isort)
- [x] #8 setuptools entrypoint and `api/v1/info` client
- [x] #12 #13 Base usage & development documentation
- [x] #13 PyPI release & documentation

**Comment by virtualtam** [comment]
First release downloadable on PyPI!

- https://pypi.python.org/pypi/shaarli-client/0.1.0
- https://python-shaarli-client.readthedocs.io/en/latest/user/installation.html
